In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
xtrain = np.array([10,12,14,15,30,35,40,65]).reshape(-1,1)
xtrain

array([[10],
       [12],
       [14],
       [15],
       [30],
       [35],
       [40],
       [65]])

In [3]:
ytrain = (xtrain >20 )
ytrain

array([[False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True]])

In [4]:
model = linear_model.LogisticRegression(C=1000)      # regularization is applied by default

In [5]:
#C : float, optional (default=1.0)
# Inverse of regularization strength; must be a positive float.
# smaller values specify stronger regularization.

In [6]:
model.fit(xtrain, ytrain)

c:\Users\REZA\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1000)

In [7]:
model.intercept_

array([-26.95768605])

In [8]:
model.coef_

array([[1.19837114]])

In [9]:
#teta= [ intercept   coef  ]

In [10]:
### predict
xtest = np.array([8,13,32,36,65])

In [11]:
t = model.coef_ * xtest  + model.intercept_      #t = teta_t_x
t

array([[-17.37071694, -11.37886124,  11.39019041,  16.18367496,
         50.936438  ]])

In [12]:
ypred = 1 / (1 + np.exp(-t))
ypred = ypred.reshape(-1,1)
ypred

array([[2.85754761e-08],
       [1.14345318e-05],
       [9.99988694e-01],
       [9.99999906e-01],
       [1.00000000e+00]])