In [1]:
from sklearn.cluster import KMeans

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
X = np.array([[1, 2], [1, 4], [5, 2], [5, 4], [9, 2], [9, 4]])

In [4]:
model = KMeans(n_clusters=3, random_state=0)

In [5]:
y = model.fit(X)

c:\Users\REZA\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\REZA\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


In [6]:
y.labels_

array([1, 1, 2, 2, 0, 0])

In [7]:
y.predict([[0, 0]])

array([1])

In [8]:
y.cluster_centers_

array([[9., 3.],
       [1., 3.],
       [5., 3.]])

In [9]:
y.cluster_centers_[0]

array([9., 3.])